baseURL = "https://designenrecherche.org/"
languageCode = "fr"
summaryLength = "10"
title = "Design en Recherche"

[markup.goldmark.renderer]
  unsafe= true

[[menu.main]]
URL = "about"
name = "L’association"
weight = 2
summary = ""
[[menu.main]]
URL = "actions"
name = "Nos actions"
weight = 3
[[menu.main]]
URL = "membres"
name = "Annuaire des membres"
summary = ""
weight = 4
[[menu.main]]
URL = "tags"
name = "Mot-clés"
summary = ""
weight = 5
[[menu.main]]
URL = "contact-adhesion"
name = "Nous contacter & Adhérer"
summary = ""
weight = 7

[params]
subtitle = "le&nbsp;réseau des&nbsp;jeunes&nbsp;chercheur·e·s en&nbsp;design"
mail = "designenrecherche@gmail.com"
credits = "Association loi 1901 à but non-lucratif."
author = "Design en Recherche"
copyright = "CC BY-SA"
description = "This is meta description"
home = "Accueil"
logo = "images/logo.png"
[params.preloader]
enable = true
preloader = ""



[taxonomies]
  tag = "tags"
  category = "categories"
