name = "Design en Rececherche"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE"
description = "Design en Rececherche theme based on Hugo port of the Themefisher’s Kross Template"
homepage = "https://gethugothemes.com/products/kross-hugo-theme/"
tags = ['landing-page', 'fast', 'light', 'white', 'modern', 'themefisher', 'hugo-theme', 'hugo-templates', 'bootstrap', 'blog', 'responsive', 'clean', 'simple', 'creative', 'contact-form', 'custom-themes', 'mobile', 'minimalistic', 'pages', 'resume', 'portfolio', 'google analytics', 'customizable', 'flexbox', 'presentation', 'product', 'theme', 'typography']
features = ['bootstrap','responsive']
min_version = "0.58.0"

[author]
  name = "Julie Blanc"
  homepage = "https://julie-blanc.fr/"

[original]
  name = "kross"
  homepage = "https://themefisher.com/products/kross-creative-portfolio-template/"