---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content/about
  label: about
  create: none
  match: "*"
- type: directory
  path: content/actions
  label: nos_actions
  create: all
  match: "**/*"
  templates:
  - actions
- type: directory
  path: content/membres
  label: membres
  create: all
  match: "**/*"
  templates:
  - membres
- type: directory
  path: content/breves
  label: breves
  create: all
  match: "**/*"
  templates:
  - breves
- type: directory
  path: content/contact-adhesion
  label: adhesion
  create: none
  match: "*"
- type: directory
  path: content/popup
  label: popup
  create: all
  match: "**/*"
  templates:
  - popup
- type: directory
  path: data
  label: data
  create: documents
  match: "*"
  new_doc_ext: yml
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.58.2
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.58.2
