---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: data/instagram.yml
  label: instagram yml
- type: directory
  path: content/instagram
  label: Résidences Instagram
  create: all
  match: "**/*"
  templates:
  - instagram
- type: directory
  path: content/actions
  label: Nos actions
  create: all
  match: "**/*"
  templates:
  - actions
- type: directory
  path: content/membres
  label: Membres
  create: all
  match: "**/*"
  templates:
  - membres
- type: directory
  path: content/breves
  label: Brèves
  create: all
  match: "**/*"
  templates:
  - breves
- type: directory
  path: content/about
  label: About
  create: none
  match: "*"
- type: directory
  path: data
  label: Data
  create: documents
  match: "*"
  new_doc_ext: yml
- type: directory
  path: content/contact
  label: Contact
  create: none
  match: "*"
- type: directory
  path: content
  label: Configuration
  create: all
  match: "*.toml"
  new_doc_ext: toml
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.58.2
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.58.2
